#pod 'AFNetworking', '~> 3.0'
#pod 'AFNetworking'
platform :ios, "7.0"
pod 'ShareSDK3'
pod 'Masonry'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
#pod 'RongCloudIMKit'
pod 'SVProgressHUD'
pod 'ZYQAssetPickerController'
#pod 'JSONKit'
pod 'SBJson', '~> 4.0.1'
#pod 'MJRefresh'
#pod 'SBJson'
pod 'MOBFoundation'
pod 'RongCloudIMKit', '2.4.8'
#pod ' Baidu-Maps-iOS-SDK', '~> 2.10.1'
pod 'BaiduMapKit'
#pod 'ZBarSDK'